samvera/questioning_authority

lib/qa/authorities/getty.rb, spec/lib/authorities_getty_spec.rb
See
http://answers.semanticweb.com/questions/31906/getty-sparql-gives-a-404-if-you-pass-accept-applicationjson
=> Set the proper accepts header for a sparql response

lib/qa/authorities/mesh.rb, spec/lib/authorities/mesh_spec.rb
`Qa::Authorities::Mesh#search` uses a non-existing class variable `@q`
in the `WHERE` clause value. This results in the value of `%` after
interpolation and all records in the table being returned.
=> Fix Mesh#search to filter results

README.md, lib/generators/qa/local/tables/mysql/mysql_generator.rb, lib/generators/qa/local/tables/tables_generator.rb, lib/qa/authorities/local.rb, lib/qa/authorities/local/mysql_table_based_authority.rb, lib/qa/authorities/local/table_based_authority.rb, spec/lib/authorities/mysql_table_based_authority_spec.rb
fixes #105 
Added the correct generator for mysql which includes creating the virtual column for lower_label in mysql syntax.  I believe this is safe since the user is specifically choosing to run the MySQL generator and we have checked their database connection to be certain it is a MySQL connection.
=> Adding a special generator and autority for mysql

README.md, lib/qa.rb, lib/qa/services.rb, lib/qa/services/rdf_authority_parser.rb, qa.gemspec, spec/fixtures/lexvo_snippet.rdf, spec/lib/services/rdf_authority_parser_spec.rb, spec/spec_helper.rb
This PR resurrects code from ScholarSphere that parses the downloadable files from Library of Congress and Lexvo to fill in the local authority tables.
=> Adding rdf authority parser for filling local authority tables

lib/qa/authorities/local/mysql_table_based_authority.rb, lib/qa/authorities/local/table_based_authority.rb
Rails 5 gives the deprecation warning:
```
DEPRECATION WARNING: #table_exists? currently checks both tables and
views. This behavior is deprecated and will be changed with Rails 5.1 to
only check tables. Use #data_source_exists? instead.
```
=> Avoid using deprecated method #table_exists?

config/initializers/authorities.rb, lib/qa/authorities/local/table_based_authority.rb
By eagerly checking, we unnecessarily make database connections even for e.g. compiling assets.
=> TableBasedAuthority should lazily check for indexes

qa.gemspec
Rubocop 1.7.0 is out now.
Pin rubocop-rspec to 1.8.0 so as to avoid the newer cops in 1.9.0
=> Loosen nokogiri dependency

.gitignore, app/controllers/qa/terms_controller.rb, lib/qa/authorities/base.rb, spec/lib/authorities/base_spec.rb
Fixes a pair of TODO items in `Authorities::Base`. A minor adjustment is made to the terms controller to catch the new errors. 
Full implementations of the Authority interface should be unchanged; for partial implementations this may reveal bugs.
----
The first commit (9a7318e) adds some documentation for the `Authorities::Base` class. A few major ToDo items remain. Quoting from the commit message:
> A few details are missing, as I'm not sure the interface is actually very clearly defined. Questions:
>
>   - Is there a return type for `#find(id)`? Possibly `Hash` or
>     `#to_json`?
>   - Does `#all` return an `Enumerable<Hash/#to_json>` or `Array`?
>   - Is `#search` a required method?
>
> If I find obvious answers to these, or come up with a proposal, I'll update as needed.
=> Make `Authorities::Base` explicitly abstract

lib/qa/authorities.rb
This makes it possible for client code to depend on authorities without introducing the entire engine (and therefore rails).
=> Require `activesupport/core_ext` from authorities

lib/qa/authorities/assign_fast/generic_authority.rb, lib/qa/authorities/geonames.rb, lib/qa/authorities/getty/aat.rb, lib/qa/authorities/getty/tgn.rb, lib/qa/authorities/getty/ulan.rb, lib/qa/authorities/loc/generic_authority.rb, lib/qa/authorities/web_service_base.rb
Many implementations already overrode `#get_json` with `#json`, since the former is not idiomatic. This simply deprecates the `#get_json` option in favor of a base `#json`.
=> Deprecate `WebServiceBase#get_json`; use `#json`

lib/qa/authorities/loc/generic_authority.rb, spec/lib/authorities/loc_spec.rb
Ran into the issue with needing `Faraday::FlatParamsEncoder`. See #101 
Ned's original PR #102 needed a slight change for the tests to work, and then a manual test on my code confirmed that LOC subject searching works as expected. 
QA + Faraday produces a proper looking url like: 
http://id.loc.gov/search/?format=json&q=Giant+panda--Breeding&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects&
Thanks Ned!
=> refactors nedhenry's patch to use flat params with LOC

.rubocop_todo.yml, README.md, app/controllers/qa/linked_data_terms_controller.rb, lib/qa.rb, lib/qa/authorities/linked_data/rdf_helper.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/test_app_templates/Gemfile.extra
Also...
* adds linkeddata gem to generated test app to avoid format error
* rename to samvera in README
=> provide better error messages and codes

db/migrate/20130917200611_create_qa_subject_mesh_terms.rb, db/migrate/20130917201026_create_qa_mesh_tree.rb, db/migrate/20130918141523_add_term_lower_to_qa_subject_mesh_terms.rb
For all migrations, this PR adds [4.2] as the version under which the migrations were created.  A version number is required for migrations to run under Rails 5.1 and later.  It cannot be present in migrations run under Rails < 5.0.
A branch, named `stable_1.2_for_rails_4.2` was created to allow bug fixes if needed to be made available for Rails 4.2.
Release 1.2 is the last one that supports Rails 4.2.  A release will be made with the migration changes in this PR and released as 1.3.  The release notes for both will be updated to reflect the Rails versions supported.
=> Add version to migrations to support rails >= 5.1

.travis.yml, README.md, qa.gemspec
* update gemspec to require at least Rails 5.0
* update Travis to test Rails 5.0 and 5.1
=> Remove 4.2 support

.rubocop_todo.yml, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/config/search_config.rb, lib/qa/authorities/linked_data/config/term_config.rb, spec/fixtures/authorities/linked_data/lod_encoding_config.json, spec/fixtures/authorities/linked_data/lod_term_id_param_config.json, spec/lib/authorities/linked_data/search_config_spec.rb, spec/lib/authorities/linked_data/term_config_spec.rb
Supports term templates in the form…
```
"{?term_uri}"              # term_uri is the entire template
"{?term_uri}.rdf"          # term_uri starts the template
"http://localhost/test_default/term?uri={?term_uri}"   # term_uri is a parameter of the template
"http://localhost/test_default/term/{?term_id}"        # term_id is a parameter of the template
```
Fixed errors:
* term_uri needs to be url encoded when it is a parameter
* term_uri should not be encoded when it is the entire template
* substitution of term id was only done when the template parameter was named term_id and not when it was named term_uri, but now happens for both
=> support the common forms used to define a term template

lib/qa/authorities/linked_data/rdf_helper.rb, lib/qa/authorities/linked_data/search_query.rb
When processing linked data authorities, we do not want to include in the results set any triples with a subject that is a blank node.  This fix filters out those results before mapping the graph to json.
=> filter out blanknodes from the results set

lib/qa/authorities/linked_data/search_query.rb, spec/lib/authorities/linked_data/search_query_spec.rb
For linked data, the configuration can specify a predicate on which to sort the results when building the json list.  Up to this point, these predicates have all been alpha strings.  With the addition of a search rank predicate that returns a numeric value, there needs to be a numeric sort.
Example: "22", "1", "215" 
alpha sort produces:  "1", "215", "22"
numeric sort produces: "1", "22", "215"
The new code checks if the both values being compared are numeric and does a numeric sort.
=> add ability to sort based on a numeric ranking predicate

lib/qa/authorities/local/mysql_table_based_authority.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/controllers/terms_controller_spec.rb
Maintain support for Rails 5.0; Add support for Rails >= 5.1:
* method `index_name_exists?(table_name, index_name, default)` had the `default` parameter removed in Rails 5.1, but it is required in Rails 5.0.  There is a check for the Rails version and it passes the default parameter when Rails is < 5.1 and doesn't when >= 5.1
Address deprecations coming with Rails 6:
* `be_success` is deprecated for Rails 6 and is being replaced with `be_successful`
=> Add support for Rails 5.1 and address deprecations coming with Rails 6

lib/qa/authorities/getty/ulan.rb, spec/lib/authorities/getty/ulan_spec.rb
Getty's server was choking on the previous multi-term SPARQL, possibly because of a URI encoding error. This PR changes the way multi-term queries are built and encoded. Also updates specs to match.
Fixes #163 
*Note*: There is some other misbehaving SPARQL, notably in the TGN authority searcher but possibly others as well. We are focusing on a ULAN fix because that's what is hampering our production rollout, but hopefully this can be used as an example for working with the others.
=> Build better SPARQL for ULAN queries with spaces in them

README.md
I know there is already an autocomplete example for [sufia](https://github.com/samvera/questioning_authority/wiki/Using-with-autocomplete-in-Sufia), but it uses linked_data endpoints, which require extra config/setup.
This example uses the loc endpoint so all you should need is 
```
bundle add 'qa'
bundle exec rails generate qa:install
```
then copy the example into a console with jQueryUI loaded, and it should work.
Might be a bit redundant since it's very similar to the sufia 6 example, but I had to write it anyway, so I figured I'd see if it was useful to anyone else.
=> jQueryUI Autocomplete example

app/controllers/qa/linked_data_terms_controller.rb, lib/qa/authorities/linked_data/find_term.rb, spec/controllers/linked_data_terms_controller_spec.rb
For backward compatibility, term data continues to return as json by default.  To request as json-ld, append parameter `format=jsonld` to the end of the request URL.
Ex. http://localhost:3000/qa/show/linked_data/oclc_fast/1914919?format=jsonld
=> allow a linked data term request to return content as json-ld

app/controllers/qa/linked_data_terms_controller.rb, config/initializers/linked_data_authorities.rb, config/routes.rb, lib/generators/qa/apidoc/templates/public/qa/apidoc/apidoc.json, lib/generators/qa/install/templates/config/initializers/qa.rb, lib/qa/authorities/linked_data.rb, lib/qa/authorities/linked_data/authority_service.rb, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/generic_authority.rb, lib/qa/configuration.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/fixtures/authorities/linked_data/lod_term_uri_param_config.json, spec/lib/authorities/linked_data/authority_service_spec.rb, spec/lib/configuration_spec.rb
* list - returns a list of the loaded linked data authorities
* reload - reload linked data configurations (does not require restart of rails server)
* fetch - retrieve a single linked data term by passing URI as a parameter
=> Extend the linked data API

app/services/qa/linked_data/graph_service.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/rdf_helper.rb, lib/qa/authorities/linked_data/search_query.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/fixtures/lod_search_with_blanknode_subjects.nt, spec/fixtures/lod_term_with_blanknode_objects.nt, spec/services/linked_data/graph_service_spec.rb
If acceptable, this replaces PR #184.  It is taking a slightly different approach on the replacement service based on feedback.
-----------------
A major refactoring of the linked data processing code is underway. The first step in the process is to extract out include code from find_term and search_query processing into separate isolated services. Work will be committed in multiple PRs to facilitate the review process and avoiding a single massive commit.
This is PR creates the first extracted service. It collects together only methods that process rdf in the new rdf_service. These were originally included through the rdf_helper module.
There are a few methods remaining in rdf_helper that will be resolved in a later refactor PR. The remaining ones will either go away or belong in another …
=> Move rdf_helper methods to graph_service

app/controllers/qa/linked_data_terms_controller.rb, app/services/qa/linked_data/authority_service.rb, config/initializers/linked_data_authorities.rb, lib/qa/authorities/linked_data.rb, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/generic_authority.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/lib/authorities/linked_data/authority_service_spec.rb
There are no code changes.  The class name of the service did change...
**FROM:**  Qa::Authorities::LinkedData::AuthorityService
**TO:**  Qa::LinkedData::AuthorityService
=> Move AuthorityService to app/services

app/models/qa/iri_template/url_config.rb, app/models/qa/iri_template/variable_map.rb, app/services/qa/iri_template_service.rb, app/services/qa/linked_data/authority_url_service.rb, lib/qa.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/models/iri_template/url_config_spec.rb, spec/models/iri_template/variable_map_spec.rb, spec/services/iri_template_service_spec.rb, spec/services/linked_data/authority_url_service_spec.rb
Working toward better separation between the classes.  The IRI related models and the IRI service that builds the URLs have good separation.  The AuthorityUrlService was put in place as a go between for the authority configuration access and the IRI models and service.  More refactoring will happen later to clean up some of the bleeding of config knowledge into the AuthorityUrlService.
=> Create models for IRI templates and use IRI template service to build URLs

app/services/qa/linked_data/graph_service.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/services/linked_data/graph_service_spec.rb
This makes graph service stateless.  A graph can be passed to any of the methods.  It does not matter if the RDF::Graph was created by this service or by some other means.
=> Convert GraphService to all class methods

.rubocop_todo.yml, app/models/qa/iri_template/url_config.rb, app/services/qa/linked_data/authority_url_service.rb, app/services/qa/linked_data/deep_sort_service.rb, app/services/qa/linked_data/graph_service.rb, app/services/qa/linked_data/language_sort_service.rb, lib/qa/authorities/linked_data/rdf_helper.rb, lib/qa/authorities/linked_data/search_query.rb, spec/lib/authorities/linked_data/search_query_spec.rb, spec/services/linked_data/deep_sort_service_spec.rb, spec/services/linked_data/language_sort_service_spec.rb
The sort process is complex.  The tests for deep_sort_service lays out the various potential sorting scenarios.  Precedence on sort...
* numeric sort, if both are integers
* simple alpha sort of one term, if both are single value
* same language list comparison, if all terms in a list are the same language or no language
* preferred language comparison only, if both lists have the at least one term in the preferred language
* calculate the comparator value for every language individually and sum to get a relative comparison of two multi-language lists (Best I could come up with.  I am open to suggestions.  In most cases, if not all, one of the earlier comparators will be selected.  This is the junk drawer of multi-lingual sorting.)
=> Refactor sort process into a service

.travis.yml
The latest version of bundler does not work with ruby 2.3.7 causing Travis to fail.  Other Samvera gems do not include this version of ruby in their Travis test matrix, so it is being removed.  Other versions of ruby and rails were updated to the latest in their minor versioning track.
=> update ruby/rails matrix for travis testing

app/models/qa/iri_template/variable_map.rb, spec/models/iri_template/variable_map_spec.rb
Encoding is primarily used to encode URIs that are part of the URL path instead of being a parameter.  But the generalized processing allows any variable to be marked as requiring URL encoding.
Also making all methods private unless they are needed in other classes.  In this refactor, that effect #default and #required?
The encoding support was in the original term_url_with_replacements which is obsolete with PR #187.  That functionality should have been pulled into variable maps then.  This PR incorporates this functionality in a broader way that allows any variable to be encoded based on configurations.
=> add ability to encode the variable value

app/models/qa/iri_template/url_config.rb, app/models/qa/iri_template/variable_map.rb, app/models/qa/linked_data/config/context_map.rb, app/models/qa/linked_data/config/context_property_map.rb, app/models/qa/linked_data/config/helper.rb, app/services/qa/linked_data/deep_sort_service.rb, spec/models/linked_data/config/context_map_spec.rb, spec/models/linked_data/config/context_property_map_spec.rb
These are the classes to process the context configuration.  They are not being used yet.
Remaining work:
* In search_config, read in and process the context configuration using these classes
* Add context_mapping_service, which will use these configurations to extract the context from the graph and return the results as json.
This PR also defines generalized helper methods for fetching configs from the config hash.  This includes fetching required configs, boolean configs, and configs values that need to be converted to a symbol.
=> add configuration models for additional context

app/models/qa/linked_data/config/context_map.rb, app/services/qa/linked_data/authority_url_service.rb, lib/qa/authorities/linked_data/config/search_config.rb, lib/qa/authorities/linked_data/config/term_config.rb, spec/fixtures/authorities/linked_data/lod_full_config.json, spec/lib/authorities/linked_data/config_spec.rb, spec/lib/authorities/linked_data/search_config_spec.rb, spec/lib/authorities/linked_data/term_config_spec.rb
Also removes obsolete methods (and related tests) that are now handled by the IriTemplate classes
=> create url_config and context_map only once

app/models/qa/linked_data/config/context_map.rb, app/models/qa/linked_data/config/context_property_map.rb, app/services/qa/linked_data/graph_service.rb, app/services/qa/linked_data/mapper/search_results_mapper_service.rb, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/config/search_config.rb, lib/qa/authorities/linked_data/config/term_config.rb, lib/qa/authorities/linked_data/generic_authority.rb, lib/qa/authorities/linked_data/search_query.rb, spec/fixtures/authorities/linked_data/lod_full_config.json, spec/lib/authorities/linked_data/config_spec.rb, spec/lib/authorities/linked_data/search_config_spec.rb, spec/models/iri_template/url_config_spec.rb, spec/models/iri_template/variable_map_spec.rb, spec/models/linked_data/config/context_map_spec.rb, spec/models/linked_data/config/context_property_map_spec.rb, spec/services/linked_data/graph_service_spec.rb
Adds:
* prefix to configs
Fixes bugs:
* fix I18n fetch with default (it was incorrect)
* fix GraphService.deep_copy which returned an array of statements instead of the graph; now returns graph as expected
Includes a bunch of cleanup in prep of next PR:
* rename lpath to ldpath (actual name of the query language)
* rename method auth_config to authority_config (more consistent)
* clean up conversion to json in search config to make it easier to extend with context
* add some tests for methods that weren’t tested
* use `describe ‘#new’ do` in tests instead of `#initialize` (more consistent)
=> add prefixes to config and some general cleanup

app/models/qa/linked_data/config/context_property_map.rb, app/services/qa/linked_data/mapper/graph_mapper_service.rb, qa.gemspec, spec/models/linked_data/config/context_property_map_spec.rb, spec/services/linked_data/mapper/graph_mapper_service_spec.rb
Also moves block processing for graph_mapper_service outside of the individual property to the set of properties.  This allows for adding context to the set of properties returned.
Example:
```
{ 
id: 1, 
label: 'The title', 
context:
{
location: '42.4488° N, 76.4763° W'
}
}
```
=> Create ldpath program for context property map

app/controllers/qa/linked_data_terms_controller.rb, app/services/qa/linked_data/mapper/context_mapper_service.rb, app/services/qa/linked_data/mapper/search_results_mapper_service.rb, lib/qa/authorities/linked_data/search_query.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/services/linked_data/mapper/context_mapper_service_spec.rb, spec/services/linked_data/mapper/search_results_mapper_service_spec.rb
**Adds:**
* context=true|false parameter to QA search URL
* uses ldpath gem to get context property's values based on ldpath in config for the property
* add context_mapper_service which fetches the context for each result and adds it to the result hash
----
**Remaining Work after this PR:**
* expand values that are URIs to include URI + label (will be in later PR)
* figure out why some ldpaths do not parse (handles this gracefully, so will be in later PR)
* ldpath gem loads (and re-loads) a new graph many times over when the data is available in the passed in graph.  Need to explore performance improvements for ldpath.
=> process additional context and add to final json results

app/models/qa/linked_data/config/context_map.rb, app/models/qa/linked_data/config/context_property_map.rb, app/services/qa/linked_data/mapper/context_mapper_service.rb, app/services/qa/linked_data/mapper/search_results_mapper_service.rb, config/locales/qa.en.yml, spec/fixtures/authorities/linked_data/lod_full_config.json, spec/lib/authorities/linked_data/config_spec.rb, spec/lib/authorities/linked_data/search_config_spec.rb, spec/models/linked_data/config/context_map_spec.rb, spec/models/linked_data/config/context_property_map_spec.rb, spec/services/linked_data/mapper/context_mapper_service_spec.rb
**Adds:**
* expands context for URIs to optionally include label and id
**Fixes:**
* group label improperly passed default to I18n
* clean up some comments
* extracts parts of longer methods into private methods to avoid rubocop complaints and/or to keep DRY
**Examples:**
Regular context (from previous PR)
```
{
property: "Authoritative Label",
values: [
"Science films"
],
selectable: true,
drillable: false
},
```
Expanding URI values in context (with this PR)
```
{
group: "Hierarchy",
property: "Narrower",
values: [
{
uri: "http://id.loc.gov/authorities/genreForms/gf2011026416",
id: "gf2011026416",
label: "Nature films"
}
],
selectable: true,
drillable: true
},
```
=> Expand context when the value is an URI and expasion was requested in the config

app/controllers/qa/linked_data_terms_controller.rb, app/controllers/qa/terms_controller.rb, spec/controllers/terms_controller_spec.rb
* For malformed requests (e.g. missing required parameter, non-supported auths/subauths), terms_controller currently returns 404, not_found.  This was changed to use 400, bad_request, which is what linked_data_terms_controller already uses for these types of errors. (Fixes issue #162)
* For both controllers, error messages now return error json when errors occur.  (Fixes Issue #58)
```
{"errors":"Required search param 'q' is missing or empty"}
```
=> Provide better error messages

lib/qa/authorities/getty/aat.rb, lib/qa/authorities/getty/tgn.rb, lib/qa/authorities/getty/ulan.rb, spec/fixtures/getty-error-response.txt, spec/lib/authorities/getty/aat_spec.rb, spec/lib/authorities/getty/tgn_spec.rb, spec/lib/authorities/getty/ulan_spec.rb
Failing URL:  http://localhost:3000/qa/search/getty/aat?q=Panathenaic%20amphorae
Logs: ` ERROR fetching Getty response: undefined method `[]' for nil:NilClass; cause: UNKNOWN`
Returns: `{}`
=> Catch and log error when response from Getty contains an error

app/models/qa/iri_template/variable_map.rb, app/services/qa/iri_template_service.rb, config/authorities/linked_data/loc.json, config/authorities/linked_data/oclc_fast.json, lib/qa/authorities/linked_data/config.rb, spec/fixtures/authorities/linked_data/lod_encoding_config.json, spec/fixtures/authorities/linked_data/lod_full_config_1_0.json, spec/fixtures/authorities/linked_data/lod_lang_defaults.json, spec/fixtures/authorities/linked_data/lod_lang_multi_defaults.json, spec/fixtures/authorities/linked_data/lod_lang_no_defaults.json, spec/fixtures/authorities/linked_data/lod_lang_param.json, spec/fixtures/authorities/linked_data/lod_min_config.json, spec/fixtures/authorities/linked_data/lod_search_only_config.json, spec/fixtures/authorities/linked_data/lod_sort.json, spec/fixtures/authorities/linked_data/lod_term_id_param_config.json, spec/fixtures/authorities/linked_data/lod_term_only_config.json, spec/fixtures/authorities/linked_data/lod_term_uri_param_config.json, spec/lib/authorities/linked_data/authority_service_spec.rb, spec/lib/authorities/linked_data/config_spec.rb, spec/lib/authorities/linked_data/search_config_spec.rb, spec/lib/authorities/linked_data/term_config_spec.rb, spec/models/iri_template/url_config_spec.rb, spec/services/iri_template_service_spec.rb
* fixes IriTemplate processing error which incorrectly converted `{?var}` to `_VALUE_`.  It now does the correct processing, which is…
* `{?var}` transforms to `var=_VALUE_`
* `{var}` transforms to `_VALUE_`
* adjusts all existing linked data config fixtures to the 2.0 format
* adds lod_full_config_1_0.json to test the auto-transform of 1.0 configs to 2.0 compliance
=> Add versioning to linked data configs

lib/qa/authorities/linked_data/search_query.rb, spec/fixtures/authorities/linked_data/lod_min_config.json, spec/lib/authorities/linked_data/generic_authority_spec.rb
It also sets id to an empty string if a predicate is specified for the id, but no value is returned.
Fixes #218
=> Default id to subject uri when missing

.circleci/config.yml, app/controllers/qa/linked_data_terms_controller.rb, app/services/qa/iri_template_service.rb, app/services/qa/linked_data/authority_url_service.rb, app/services/qa/linked_data/language_service.rb, lib/qa/authorities/linked_data/config/search_config.rb, lib/qa/authorities/linked_data/config/term_config.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/features/linked_data/language_spec.rb, spec/fixtures/authorities/linked_data/lod_full_config.json, spec/fixtures/lod_lang_search_enesfrde.rdf.xml, spec/fixtures/lod_lang_search_sv.rdf.xml, spec/lib/authorities/linked_data/config_spec.rb, spec/lib/authorities/linked_data/search_config_spec.rb, spec/lib/authorities/linked_data/term_config_spec.rb, spec/services/iri_template_service_spec.rb, spec/services/linked_data/language_service_spec.rb
Adds a few other improvements…
* allow * as a wildcard for language processing which will prevent filtering of literals by language
* do not include parameters that do not have a value when building URLs
* clean template built URL to remove any occurances of ?&, &&, or ending with &
=> allow language to be specified in the http accept_language header

app/models/qa/linked_data/config/context_property_map.rb, app/services/qa/linked_data/ldpath_service.rb, lib/generators/qa/install/templates/config/initializers/qa.rb, lib/qa.rb, lib/qa/authorities/linked_data/config.rb, lib/qa/configuration.rb, spec/lib/configuration_spec.rb, spec/models/linked_data/config/context_property_map_spec.rb, spec/services/linked_data/ldpath_service_spec.rb
Extract out the ldpath processing into the ldpath service.  This facilitates the next step which will be using ldpath with linked data configuration predicates specified outside the extended context section of the configuration.
This includes the ability to tell ldpath not to look outside the passed in graph.  Otherwise, ldpath may make multiple network calls per single QA request.  In many, if not most, cases, this is not performant.  By default, this is set to true which prevents ldpath from making additional network calls.
=> extract out ldpath processing into ldpath service

spec/lib/authorities/linked_data/find_term_spec.rb, spec/lib/authorities/linked_data/generic_authority_spec.rb, spec/lib/authorities/linked_data/search_query_spec.rb
These were tested in GenericAuthority because typically they are called as a delegate in this class.  But it is easier to read the tests when they are separated out to those for search and those for find.  So they were moved to the specs for classes that implement the search and find methods.
=> Move search and find tests SearchQuery and FindTerm specs

app/services/qa/linked_data/mapper/graph_ldpath_mapper_service.rb, app/services/qa/linked_data/mapper/graph_predicate_mapper_service.rb, app/services/qa/linked_data/mapper/search_results_mapper_service.rb, config/authorities/linked_data/oclc_fast.json, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/config/search_config.rb, lib/qa/authorities/linked_data/search_query.rb, spec/services/linked_data/mapper/graph_ldpath_mapper_service_spec.rb, spec/services/linked_data/mapper/graph_predicate_mapper_service_spec.rb
NOTE: Processing of the search config with results specified using predicates was NOT removed.  It is deprecated for backward compatibility.
=> switch search configs to use ldpath instead of predicates for specifying results

.circleci/config.yml, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/config/term_config.rb, lib/qa/authorities/linked_data/find_term.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/fixtures/authorities/linked_data/lod_lang_defaults.json, spec/fixtures/authorities/linked_data/lod_lang_multi_defaults.json, spec/fixtures/authorities/linked_data/lod_lang_no_defaults.json, spec/fixtures/authorities/linked_data/lod_lang_param.json, spec/fixtures/authorities/linked_data/lod_term_uri_param_config.json, spec/lib/authorities/linked_data/find_term_spec.rb
The particular stubbing that is happening when using graph filtering in QA does not seem to mind if bogus data is used.  But as we move to ldpath, it is looking for real data in the graph.
This is prep work for moving findterm to use ldpath.
=> update tests to use real values found in the data

.circleci/config.yml, app/services/qa/linked_data/deep_sort_service.rb, app/services/qa/linked_data/graph_service.rb, app/services/qa/linked_data/language_service.rb, app/services/qa/linked_data/language_sort_service.rb, app/services/qa/linked_data/mapper/search_results_mapper_service.rb, lib/qa/authorities/linked_data/config/term_config.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/rdf_helper.rb, lib/qa/authorities/linked_data/search_query.rb
**[WIP]  This is marked WIP because it is better to merge PR #230 first and then rebase this PR before merging it.**
----
Prep for using ldpath with findterm:
* provide access to full config/authority
* use class variables to identify services used in findterm
* use Qa::LinkedData::LanguageSortService for sorting an array of literals instead of rdf_helper module
Part of the goal for the refactoring is to remove the need for the rdf_helper include.  The code in that module should be replaced by service calls instead.  This refactor did this for language sorting.  The next refactor should swap out more of the other methods.
=> Basic refactoring of findterm to make it easier to update and more inline with searchquery

app/controllers/qa/linked_data_terms_controller.rb, app/services/qa/linked_data/authority_service.rb, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/config/search_config.rb, lib/qa/authorities/linked_data/config/term_config.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/lib/authorities/linked_data/config_spec.rb, spec/lib/authorities/linked_data/search_config_spec.rb, spec/lib/authorities/linked_data/term_config_spec.rb, spec/services/linked_data/authority_service_spec.rb, spec/spec_helper.rb, spec/support/matchers/include_hash.rb
http://localhost:3000/qa/list/linked_data/authorities
http://localhost:3000/qa/list/linked_data/authorities?details=false
Produces output like...
```
[ 'oclc_fast', 'loc', ...]
```
http://localhost:3000/qa/list/linked_data/authorities?details=true
Produces output like...
**Term with no subauthorities OR fetching term across subauthorities**
```
{
"label":"oclc_fast term (QA)",
"uri":"urn:qa:term:oclc_fast",
"authority":"oclc_fast",
"action":"term",
"language":["en"]
},
```
**Search across subauthorities**
```
{
"label":"oclc_fast search (QA)",
"uri":"urn:qa:search:oclc_fast",
"authority":"oclc_fast",
"action":"search",
"language":["en"]
},
```
**Search within a subauthority**
```
{
"label":"oclc_fast search topic (QA)",
"uri":"urn:qa:search:oclc_fast:topic",
"authority":"oclc_fast", …
```
=> add option to include authority details when getting list of authorities

config/authorities/linked_data/loc.json, lib/qa/authorities/linked_data/find_term.rb, spec/fixtures/lod_loc_term_found.rdf.xml, spec/lib/authorities/linked_data/find_term_spec.rb
This was a regression from the output prior to refactoring that showed up in PR #233.
The tests didn't catch the bug because rspec turned the RDF::URI to a string in the related tests.  The tests were updated to specifically test for the subject uri and one of the other uris `to be_kind_of String`.
=> subject uri, broader, narrower should be string instead of RDF::URI in json results

app/controllers/qa/linked_data_terms_controller.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/lib/authorities/linked_data/find_term_spec.rb, spec/lib/authorities/linked_data/search_query_spec.rb
Add `”performance”` and `”results”` keys to full output of `SearchQuery #search` and `FindTerm #find`, which include the new performance stats and the original set of results, respectively.
**For search...**
```
{
"performance":
{
"result_count":6,
"fetch_time_s":0.148102,
"normalization_time_s":5.0e-06,
"total_time_s":0.14810700000000002
}
results”:{ _same_as_before_}
}
```
**For term fetch...**
```
{
"performance":
{
"predicate_count":6,
"fetch_time_s":0.148102,
"normalization_time_s":5.0e-06,
"total_time_s":0.14810700000000002
}
results”:{ _same_as_before_}
}
```
=> add option to include performance statistics in the returned result

lib/qa/authorities/linked_data/find_term.rb, spec/fixtures/lod_loc_second_term_found.rdf.xml, spec/lib/authorities/linked_data/find_term_spec.rb
Fixes a bug where the uri, once set, was used for all subsequent calls involving find by id.
=> reset uri with every call to find

lib/qa/authorities/linked_data/find_term.rb, spec/lib/authorities/linked_data/find_term_spec.rb
=> determine is loc special processing should be done based on template uri instead of authority name

app/controllers/qa/linked_data_terms_controller.rb, lib/qa.rb, lib/qa/authorities/linked_data/find_term.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/fixtures/lod_loc_term_bad_id.rdf.xml, spec/fixtures/lod_oclc_term_bad_id.nt, spec/lib/authorities/linked_data/find_term_spec.rb
Closes #247
In this case, the data can’t be normalized because the requested ID does not match the ID in the graph for the term.  This prevents the extraction of the URI from the graph based on the ID.
With this fix, an exception is raised when it happens so the error can be reported back to users.  This fails more gracefully than the previous failure which just returned empty data for uri, id, and label.
=> Raise an exception if data can’t be normalized

spec/lib/authorities/linked_data/find_term_spec.rb
There was a refactor of the stubbing in find_term_spec.rb in PR #249 that was not done PR #248.  When both merged, this broke one of the tests in the second PR.
This fixes that broken test by applying the same refactor to that test.
=> Fix the test that broke during merge of multiple PRs

lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/lib/authorities/linked_data/find_term_spec.rb, spec/lib/authorities/linked_data/search_query_spec.rb
New fetch performance data...
```
"performance":{
"predicate_count":19,
"fetch_time_s":1.563339,
"normalization_time_s":8.0e-06,
"fetched_bytes":241308,
"normalized_bytes":19920,
"fetch_bytes_per_s":154354.23794839124,
"normalization_bytes_per_s":2490000000.0,
"total_time_s":1.563347}
```
New search performance data...
```
"performance":{
"result_count":20,
"fetch_time_s":1.0732,
"normalization_time_s":1.75178,
"fetched_bytes":107856,
"normalized_bytes":2159,
"fetch_bytes_per_s":100499.44092433843,
"normalization_bytes_per_s":1232.4606971195014,
"total_time_s":2.82498}
```
=> add bytes and bytes/s to performance data

app/services/qa/linked_data/ldpath_service.rb, config/authorities/linked_data/loc.json, lib/qa/authorities/linked_data/config/term_config.rb, lib/qa/authorities/linked_data/find_term.rb, spec/lib/authorities/linked_data/term_config_spec.rb, spec/services/linked_data/ldpath_service_spec.rb
Closes #244
This supports the id being defined with multiple paths...
```
"id_ldpath":       "loc:lccn | madsrdf:code",
```
such that the id value can come from either path.
=> allow id to be identified by multiple paths using ldpath

app/models/qa/linked_data/config/context_property_map.rb, lib/generators/qa/install/templates/config/initializers/qa.rb, lib/qa/configuration.rb, spec/lib/configuration_spec.rb, spec/models/linked_data/config/context_property_map_spec.rb
Closes 255
Adds `:property_map_default_for_optional` to `Qa.config` with a default value of `false` for backward compatibility.
=> allow property_map.optional? default value to be configurable

app/services/qa/linked_data/graph_service.rb, spec/services/linked_data/graph_service_spec.rb
Multiple webmock tests, but not all, were randomly failing on CCI only.  These were first seen when PR #259 was merged into master, but were not caused by the PR.  They appeared to be related to dependency changes or infrastructure change at CCI.  
After extensive investigation (many thanks to @botimer and @jrgriffiniii), it was determined that the addition of rest-client gem caused an error to surface.  The error occurs because when rest-client gem is present, RDF::Graph.load method returns its error messages in a different form.  Sometimes the error message includes parentheses around the error code (i.e., "... (503)") and sometimes not (i.e., "... 503").  QA parses the error code from the error message to pass back a more meaningful error to the caller.  
QA was doing a positional …
=> allow error from RDF::Graph to be parsed with or without paren around code

app/controllers/qa/linked_data_terms_controller.rb, lib/qa/authorities/discogs/discogs_translation.rb, lib/qa/authorities/discogs/generic_authority.rb, lib/qa/authorities/linked_data/find_term.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/lib/authorities/discogs/generic_authority_spec.rb
This impacts all authorities supported through the linked data module (i.e., lib/qa/authorities/linked_data/find_term) and the discogs authority (i.e. lib/qa/authorities/discogs).
=> add ability to return a single term as n3 format for linked data

CHANGELOG.md, lib/qa/version.rb
Change log...
* add ability to return a single term as n3 format for linked data
* allow error from RDF::Graph to be parsed with or without parentheses around
* remove CircleCI ruby/rails version defaults (maintenance)
* adjust queries for TGN to use TGN scheme and not ULAN
=> Prep for release 4.2.1

CHANGELOG.md, lib/qa/version.rb
Includes update to discogs authority to set URI in search results to…
* real discogs URI whenever available
* discogs URL when not
Fetch data will use the same URI/URL as the subject_uri for triples when linked data is requested.
=> prep for release 4.2.4

app/controllers/qa/linked_data_terms_controller.rb, app/services/qa/linked_data/authority_url_service.rb, app/services/qa/linked_data/request_header_service.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/lib/authorities/linked_data/find_term_spec.rb, spec/lib/authorities/linked_data/search_query_spec.rb, spec/services/linked_data/authority_url_service_spec.rb, spec/services/linked_data/request_header_service_spec.rb
The list of parameters that are passed to search and find methods for the linked data module are long.  There is a need to add another parameter.  In prep for that, this refactors the optional parameters into a single request_header parameter.  This same change is also in AuthorityUrlService which builds the URLs used in search and find and is the primary consumer of the optional params.
All other changes are in the callers of these methods, which is coming from LinkdedDataTermsController actions.
The longer individual parameter lists are deprecated.
=> refactor optional attributes for linked data search/fetch to pass as hash

CHANGELOG.md, lib/qa/version.rb
* refactor to single request_header parameter for search and find methods; multi-parameters are still supported, but deprecated
* refactor Discogs to provide the same format for extended context as the linked data module
=> prep for release 4.2.5

.circleci/config.yml, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/linked_data/config/search_config.rb, spec/fixtures/authorities/linked_data/lod_full_config.json, spec/lib/authorities/linked_data/config_spec.rb, spec/lib/authorities/linked_data/search_config_spec.rb
* service_uri - the uri for the authority provider that allows the service to send general information as part of a search query or term fetch
* total_count_ldpath - the ldpath within the results graph that holds the total number of available search result records.  The service_uri will be the subject URI of the triple holding this value.
These configs identify parameters that are passed to QA and play a specific role.
* start_record - number of the first record returned in search results
* requested_records - number of records to return in search results
start_record and requested_records are used to identify the page number and the number of records to display on a page.  For example...
```
start_record = 1 AND requested_records = 10 equates to page 1 records 1..10
start_record = 11 AND …
```
=> add new configurations for identifying parameters related to pagination of linked data results

app/controllers/qa/linked_data_terms_controller.rb, app/services/qa/linked_data/performance_data_service.rb, app/services/qa/linked_data/request_header_service.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/controllers/linked_data_terms_controller_spec.rb, spec/lib/authorities/linked_data/find_term_spec.rb, spec/lib/authorities/linked_data/search_query_spec.rb, spec/services/linked_data/performance_data_service_spec.rb, spec/services/linked_data/request_header_service_spec.rb
Search queries and term fetch requests have the option to return performance data.  This applies to the linked data module.  Previously that output was generated in the SearchQuery class and separately in the FindTerm class.  The output generation process was moved to a service that both these classes now use.
Related work #281
=> move performance data output generation to a service

lib/qa/authorities/local/mysql_table_based_authority.rb
Preparing for Rails 6.
https://github.com/samvera/questioning_authority/pull/291
qa gemspec still allows rails 5.0, so we will leave the "else" condition for rails 5.0 there (although rails 5.0 makes the third param optional and may work without it too, if it ain't broke why fix it).
=> use new index_name_exists? method signature if rails6 too

spec/controllers/linked_data_terms_controller_spec.rb, spec/controllers/terms_controller_spec.rb
Preparing for Rails6. In Rails6, response.content_type includes entire content type header, like 'application/n-triples; charset=utf-8' when previously it was just application/n-triples, which is what tests are expecting. This is only a change to test code, not actual code under test, to make tests test the right thing under a future Rails 6.0.
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#actiondispatch-response-content-type-now-returned-content-type-header-as-it-is
https://github.com/samvera/questioning_authority/pull/291
https://circleci.com/gh/samvera/questioning_authority/1295
=> use response.media_type instead of .content_type in tests

.circleci/config.yml, qa.gemspec
With circleci testing. 
Experimental PR to see if it somehow passes, or what the errors look like if it doesn't. I haven't been able to get tests to run locally at all, so this is kind of a shot in the dark just to see what happens. 
Ref #287
=> Rails6 allowed

app/services/qa/linked_data/request_header_service.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, spec/services/linked_data/request_header_service_spec.rb
When there is a heavy load of requests, logging can be interspersed for the various requests.  It is difficult to tell which log message applies to which request.  Adding a request id allows each log message to be prefixed with the id.
The request was also added to the request_header to allow downstream apps to have access to the request if they need additional information.
=> add a request id to the search and find request headers

app/services/qa/linked_data/graph_service.rb, app/services/qa/linked_data/request_header_service.rb, lib/generators/qa/install/templates/config/initializers/qa.rb, lib/qa/authorities/linked_data/find_term.rb, lib/qa/authorities/linked_data/search_query.rb, lib/qa/configuration.rb, qa.gemspec, spec/controllers/linked_data_terms_controller_spec.rb, spec/services/linked_data/request_header_service_spec.rb
Marks the start of each linked data search/find request.  Unless `Qa.config.suppress_ip_data_from_log`, this marker will include IP address, city, state, and country as reported by the `geocoder` gem.
NOTE: This also removes inclusion of the request_id directly in the logging messages.  To include request_id, it is recommended that you set up the logger to do this automatically in `config/environments/development.rb` (or relevant env file) using…
```
config.log_tags = [:request_id]
```
=> optionally include IP info at start of search/find linked data requests

app/services/qa/linked_data/request_header_service.rb
if request location cannot be retrieved from the http request, make sure the logging is handled gracefully
=> make ip logging more robust

lib/qa/authorities/geonames.rb, spec/lib/authorities/geonames_spec.rb
Geonames now uses HTTPS URIs for its resources. Since QA constructs the URIs
from JSON ids manually, it missed this change. The update fixes subject
mismatches for clients.
Fixes #306.
=> Update Geonames URIs to https

qa.gemspec
Prior to this commit, when running the EngineCart build task locally,
I encountered the following error:
```console
Could not find "README.md" in any of your source paths. Your current source paths are:
$HOME/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-5.2.0/lib/rails/generators/rails/app/templates
```
With some poking around, I found the following:
> You may be using rails 5.2.0. Upgrading to 5.2.3 or later solves the problem.
>
> https://www.robotex.de/de/tags/dummy-app
With this commit, I'm still allowing upstream implementers to use Rails 5.2.0,
however, building the test app requires the generators to better behave. This
should have no impact on existing implementations.
=> Updating Rails development dependency

lib/qa/authorities/geonames.rb, spec/lib/authorities/geonames_spec.rb
Prior to this commit, the URLs are hard-coded. This is a quick fix to
expose those URLs as configurable. There is likely a more generalized
approach to consider in the configuration, but this gets the problem
unstuck.
Closes samvera/hyrax#4284
=> Adding config option for Geonames URLs

lib/qa/authorities/loc/generic_authority.rb, lib/qa/authorities/loc_subauthority.rb, spec/controllers/terms_controller_spec.rb, spec/lib/authorities/loc_spec.rb
Fixes #320
LoC is now redirecting `http` requests to `https`, and QA is not following redirects, so applications would see HTTP 500 errors, because the response would not parse as JSON. This commit fixes that issue by changing all the LoC urls to use `https`.
=> Changes LoC authorities to use https

lib/qa/authorities/loc_subauthority.rb, spec/controllers/terms_controller_spec.rb, spec/lib/authorities/loc_spec.rb
Fixes #320 (again).
While the URL to search LoC authorities has changed to https, the URL for authorities (used to limit results to that authority) has not.
=> Fixes issue limiting LoC results to an authority

app/services/qa/linked_data/authority_url_service.rb, spec/services/linked_data/authority_url_service_spec.rb
Fixes 326
LinkedData::AuthorityUrlService #combined_substitutions updated the passed in replacements hash.  It now clones the hash to avoid having this side-effect.
NOTE: The new test fails without the fix in place.
@samvera/hyrax-code-reviewers
=> do not overwrite passed in replacements hash

config/authorities/linked_data/oclc_fast.json, spec/controllers/linked_data_terms_controller_spec.rb, spec/lib/authorities/linked_data/find_term_spec.rb, spec/services/linked_data/authority_url_service_spec.rb
Fixes #327 
Encoding the query before passing it to OCLC FAST avoids the timeout.  There are a few other changes that bring the config in line with changes in other configs.  These are annotated in the code view of the PR.
@samvera/hyrax-code-reviewers
=> encode query for linked data access to OCLC FAST

.circleci/config.yml, qa.gemspec
This PR does nothing except change the gemspec to allow Rails 6.1. Curious if CI will pass like this?
I am unable to run tests locally per #331, so this is a way to see if CI will run tests for me to see what happens, sorry. 
Closes #330
=> allow rails 6.2

.circleci/config.yml, README.md
Adds Circle CI step that fails if branch name is master
Fixes #336
Adds information for branch naming conventions to contributing section of the README.
Fixes #337
=> prevent master branch; provide info on branch naming in README

app/controllers/qa/terms_controller.rb, config/routes.rb, spec/controllers/terms_controller_spec.rb, spec/fixtures/authorities/authority_U.yml
Prior to this PR, the way to get the details of a term was to use the `show` action.  The term is identified by appending the term's id to the end of the URL request path in the form:
```
http://my.app/qa/show/vocab/123
```
This approach does not work for IDs that are URIs.  The slashes in the URI get interpreted as part of the path.  The introduction of the `fetch` action allows the URI to be passed in as a parameter instead of as part of the path.
```
http://my.app/qa/fetch/vocab?uri=http://my.vocab/terms/123
```
_NOTE: The linked data module already uses `fetch` to pass in a URI since almost all IDs are URIs._
=> add fetch action allowing for uri parameter

qa.gemspec
Pinning Faraday to postpone upgrade to 2.0.  ActiveFedora currently pins to `’~> 0.12’` which is more strict, but compatible with the current pin in QA to `’< 2.0’`.
The 2.0 upgrade requires a configuration that is not supported in earlier versions.  See [upgrade doc](https://github.com/lostisland/faraday/blob/main/UPGRADING.md) for more information.
=> pin Faraday gem to < 2.0

app/controllers/qa/terms_controller.rb, app/services/qa/pagination_service.rb, config/initializers/mime_types.rb, spec/controllers/terms_controller_spec.rb, spec/services/pagination_service_spec.rb
This implementation follows json-api recommendations with:
* response[‘data’] = the results
* response[‘meta’][‘page’] = pagination statistics (i.e., page_offset, page_limit, actual_page_size, total_num_found)
* response[‘links’] = set of links for pagination (i.e., self, first, prev, next, last)
* response[‘errors’] = any errors with requested page_offset or page_limit (only included if there are errors)
Reference:
* [Pagination](https://jsonapi.org/format/#fetching-pagination) section of [Latest JsonAPI spec](https://jsonapi.org/format/)
* [Pagination Links](https://jsonapi.org/examples/#pagination) example
NOTE: For backward compatibility, if the format is JSON (default) and neither page_offset or page_limit are set, then only the results, including all results, will be returned.
=> add pagination service and use it for yml file authorities

config/initializers/authorities.rb, config/initializers/linked_data_authorities.rb
My Rails 6.1.3.2 app that uses `qa` gem has this deprecation warning on startup in development mode:
```
DEPRECATION WARNING: Initialization autoloaded the constants Qa::LinkedData and Qa::LinkedData::AuthorityService.
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Qa::LinkedData, for example,
the expected changes won't be reflected in that stale Module object.
These autoloaded constants have been unloaded.
In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:
Rails.application.reloader.to_prepare do
end
That block runs when the …
```
=> wrap initialization in reloader.to_prepare to avoid autoload deprecation warning in some cases

config/initializers/authorities.rb, config/initializers/linked_data_authorities.rb, lib/qa/version.rb
Reverts samvera/questioning_authority#349
Based upon the issue [I was seeing in Hyrax](https://github.com/samvera/questioning_authority/pull/349#issuecomment-1030326627) trying to use the new release of QA, I think it would be good to revert this change, cut a new release, and open an issue to take a deeper look at how to resolve this.
=> Revert "wrap initialization in reloader.to_prepare to avoid autoload deprecation warning in some cases"

.circleci/config.yml
Resolves #352 and addresses the following:
- Updates the Samvera CircleCI Orb to release 1.0.1
- Updating bundler to release 2.3.10 for CircleCI
- Ensuring that the `libsqlite3-dev` is installed for the CircleCI container
- Updating the Ruby releases in the CircleCI build matrix to 2.7.5, 2.6.9 and 2.5.9
=> Ensures that CircleCI executes nightly test suites are executed

qa.gemspec
I am interested in upgrading an app that uses the qa gem to use faraday 2.x, to get advantage of new features and bugfixes, but I can't do that if qa doesn't allow it. 
tests seem to pass fine with latest faraday 2. I believe the issue that resulted in limiting to faraday 1.x only at 8378088 may have been resolved in faraday 2.0.1. I have excluded Faraday 2.0.1 as allowed, following advice at [Faraday upgrading guide](https://github.com/lostisland/faraday/blob/main/UPGRADING.md) "We strongly suggest you to skip version 2.0 and instead use version 2.0.1 or greater."
=> Allow Faraday 2.x again

lib/qa/authorities/assign_fast/generic_authority.rb, lib/qa/authorities/crossref/generic_authority.rb, lib/qa/authorities/discogs/generic_authority.rb, lib/qa/authorities/linked_data/generic_authority.rb, lib/qa/authorities/loc/generic_authority.rb, lib/qa/authorities/local/file_based_authority.rb, lib/qa/authorities/local/table_based_authority.rb, lib/qa/authorities/oclcts/generic_oclc_authority.rb, spec/controllers/terms_controller_spec.rb
`Lint/MissingSuper` wants us to call `super()` at the beginning of these initializers.
I'm mindful of the discussion at https://github.com/rubocop/ruby-style-guide/issues/809 but this looks to me like a harmless change.
=> Call `super()` in a bunch of initializers

spec/lib/authorities/getty/aat_spec.rb, spec/lib/authorities/getty/tgn_spec.rb, spec/lib/authorities/getty/ulan_spec.rb
In Ruby 3.1, the `https://github.com/ruby/ruby/tree/master/lib/error_highlight` gem will start highlighting the part of the code that breaks. Let's match both the old-style and new-style error using a clever regex.
=> Use a regular expression to match error messages

lib/qa/authorities/geonames.rb, lib/qa/authorities/linked_data/config.rb, lib/qa/authorities/mesh_tools/mesh_data_parser.rb
Three trivial changes prompted by Rubocop:
- a private method name in `lib/qa/authorities/linked_data/config.rb`;
- a comment in `lib/qa/authorities/geonames.rb`;
- another comment turning off the `Metrics/CyclomaticComplexity` cop for `lib/qa/authorities/mesh_tools/mesh_data_parser.rb` which appears to me just fine as it is.
=> Trivial rubocop changes

Gemfile, qa.gemspec, spec/spec_helper.rb
I understand the consensus is that these are more trouble than they're worth. Getting rid of them is an easy way to make the code compatible with Ruby 3.1.
(_Note_: If it is important that we keep them, we will just need to ensure that the method that turns on test coverage is only invoked once. I do believe I know how to do this.)
=> Remove simplecov and coveralls

.circleci/config.yml, .rubocop.yml, README.md, qa.gemspec, spec/test_app_templates/Gemfile.extra
- Adds support for Ruby 3.0 and 3.1, as well as Rails 6.1
- Three changes to the enginecart test app to support Ruby 3.1 with Rails 6.1:
- Opts into `'mail', '>= 2.8.0.rc1'`
- Holds back `psych < 4`
- `'net-smtp', require: false`
This should address both #345 and #331.
=> Ruby 3.1 and Rails 6.1 support

.github_changelog_generator, CHANGELOG.md, lib/qa/version.rb
[Full Changelog](https://github.com/samvera/questioning_authority/compare/v5.8.1...5.9.0)
**Closed issues:**
- Configure nightly CircleCI test suite executions [\#352](https://github.com/samvera/questioning_authority/issues/352)
- Support Rails 6.1 releases [\#344](https://github.com/samvera/questioning_authority/issues/344)
**Merged pull requests:**
- Ruby 3.1 and Rails 6.1 support [\#371](https://github.com/samvera/questioning_authority/pull/371) ([eddierubeiz](https://github.com/eddierubeiz))
- Replace URI.unescape with CGI.unescape [\#369](https://github.com/samvera/questioning_authority/pull/369) ([eddierubeiz](https://github.com/eddierubeiz))
- Change open\(url\) to URI.open\(url\) [\#367](https://github.com/samvera/questioning_authority/pull/367) …
=> release 5.9.0

.circleci/config.yml, qa.gemspec, spec/lib/authorities/discogs/generic_authority_spec.rb, spec/spec_helper.rb, spec/test_app_templates/Gemfile.extra
CI build started failing with no changes to local code.
See #373. 
We don't entirely understand why; clearly some change with latest release of dependencies or ruby itself (since there were no changes to local code), but we don't entirely understand what/why.  
- Only Rails 6.1+ works with psych 4, although older rails doens't know it, being unmaintained, and needs a local pin to psych 3
* Don't know why this at one point passed, even after psych 4 had been released.
- Fix test of raw serialized JSON
* In some versions of ruby/dependencies, there is a literal `&` in raw serialized JSON source; in other versions, it's a `\u0026` (which should mean the same thing once parsed). We don't understand why this differs between different ruby/rails versions, or why it started differing at some …
=> Fix CI build

.github_changelog_generator, CHANGELOG.md, lib/qa/version.rb
CHANGELOG created per README instructions with `github_changelog_generator` tool.
=> prepare for 5.10 release

.circleci/config.yml
Locally tests passed under Rails 7.0 and Ruby 3.2 with no changes to code.
=> Run CI with Ruby 3.2

lib/qa/data/TGN_LANGUAGES.xml
At some point nokogiri started actually paying attention to the `encoding` attribute in the <?xml> decleration in a way that made it parse improperly when it wrongly said "ASCII" when data actually had UTF-8
In `nokogiri-1.15.4-arm64-darwin` this discrepency was making code fail, with nokogiri failing to parse the file; even though this .XML file hasn't changed in 10 years, and it used to work fine.
=> Fix TGN_LANGAUGES.xml encoding attribute to be properly UTF-8

.circleci/config.yml, Gemfile, lib/qa/authorities/getty/aat.rb
Not sure how this used to pass but started failing with no code changes, but rubocop currently complains:
```
lib/qa/authorities/getty/aat.rb:57:17: C: [Correctable] Rails/Presence: Use cause.presence || 'UNKNOWN' instead of cause.present? ? cause : 'UNKNOWN'.
cause = cause.present? ? cause : 'UNKNOWN'
```
Just in case that takes care of some of any remaining problems. 
Eg Rails `7.1.3.4` instead of previously `7.1.1`
And Ruby `3.2.4` instead of previously `3.2.2`
Rails 7.1 can use rack 3.  You need puma 6 not puma 5 for rack 3. 
I don't really understand why we weren't getting puma 6 already -- as far as I can tell nothing in the requirements tree should have prevented puma 6, and I get puma 6 on my local copy when I run with ruby 3.2 and rails 7.1!
BUT on CircleCI, we were getting a …
=> Get CI green

lib/qa/authorities/assign_fast/generic_authority.rb, spec/controllers/terms_controller_spec.rb, spec/lib/authorities/assign_fast_spec.rb
We are pretty sure that the AssignFAST API sort ordering changed sometime in last 1-2 months, to become a strictly alphabetical sort, that our metadata staff found difficult to use for their use cases. 
OCLC was not able to confirm or deny that it had changed, but did offer this un-doc'd API query parameter to provide usage-based ordering. `&sort=usage+desc`
This restored API results to what our staff believes it may have been similarly. 
I think this change is necessary to keep the QA AssignFAST authority acting the way users have expected, and in a way useful for the use cases that people were were using it for. 
My own institution has locally patched to get this behavior already.
=> Specify AssignFAST sort order to get expected and previous result ordering

app/controllers/qa/linked_data_terms_controller.rb, app/controllers/qa/terms_controller.rb, lib/qa.rb, lib/qa/authorities/base.rb, lib/qa/authorities/linked_data/generic_authority.rb, lib/qa/authorities/loc/generic_authority.rb, lib/qa/authorities/loc_subauthority.rb, lib/qa/authority_request_context.rb, lib/qa/authority_wrapper.rb, spec/lib/authorities/loc_spec.rb
24776bc3a47d6211383874f06544ba5a9225ede9
Prior to this commit, we used different initialization logic for linked
data authorities and non-linked data.  Further, the initialization logic
was locked away inside of a controller.
With this commit, we expose a method that provides consistent
initialization logic; albeit with different returned classes that have
slightly different implementation nuances.  The application can then
rely on that and we can share initialization logic across controllers
and also expose a method that allows non-controller initialization to
begin to follow the same logic pathway.
Where are the tests?  The initializations are covered by controller
tests, so I have chosen not to write new ones.
There is further work to do because LinkedData and non-LinkedData there
are …
=> Extracting `Qa.authority_for`

.circleci/config.yml, Gemfile, spec/test_app_templates/Gemfile.extra
`concurrent-ruby` 1.3.5 breaks on Rails versions below 7, so we're pinning this to 1.3.4.
This is a common fix for this problem; see also e.g. https://github.com/samvera/hyrax/pull/6989
=> Pin `concurrent-ruby`

config/authorities/assign_fast/oclc_assign_fast.json
It turns out QA does follow redirects within the same host; we won't be needing this setting.
=> Remove unnecessary setting
