app/controllers/qa/terms_controller.rb
lib/qa/authorities.rb
lib/qa/authorities/assign_fast.rb
lib/qa/authorities/assign_fast/generic_authority.rb
lib/qa/authorities/assign_fast_subauthority.rb
spec/controllers/terms_controller_spec.rb
spec/fixtures/assign-fast-noheader.json
spec/fixtures/assign-fast-noresults.json
spec/fixtures/assign-fast-oneresult.json
spec/fixtures/assign-fast-topical-result.json
spec/lib/authorities/assign_fast_spec.rb

FYI: to get this working I had to modify terms_controller to account for a camelcased authority class. That's in a separate commit; happy to squash it if that's best

New authority - a wrapper for FAST autocomplete service

---

.gitignore
lib/qa/authorities/getty.rb
lib/qa/authorities/getty/aat.rb
lib/qa/authorities/getty/tgn.rb
lib/qa/authorities/getty/ulan.rb
spec/fixtures/getty-tgn-find-response.json
spec/fixtures/getty-ulan-find-response.json
spec/fixtures/tgn-response.txt
spec/fixtures/ulan-response.txt
spec/lib/authorities/getty/aat_spec.rb
spec/lib/authorities/getty/tgn_spec.rb
spec/lib/authorities/getty/ulan_spec.rb

Added support for  Getty TGN (search and find) by creating a new tgn.rb class.  Amended aat.rb to add the sub-authority name and getty.rb to deal with the sub-authority and choose the correct class. This is my first ever Hydra pull request.

Added support for  Getty TGN (search and find). 

---

lib/generators/qa/local/tables/tables_generator.rb

Fixes #103 
I tried creating the correct code based on only the generator, but could not succeed.  So I added a gsub to add the class name.

Changing the generator to link to the name spaced table.

---

lib/qa/authorities/local/mysql_table_based_authority.rb
lib/qa/authorities/local/table_based_authority.rb
spec/lib/authorities/mysql_table_based_authority_spec.rb
spec/lib/authorities/table_based_authority_spec.rb

Specify table name for TableBasedAuthority

---

app/controllers/qa/terms_controller.rb
spec/controllers/terms_controller_spec.rb

Needed for a local QA that uses a SearchBuilder.

Add search method to see if wants the controller with the request.

---

README.md

Gives an example of creating an authority in an application.

Update README with info on creating own authority versus sub-authority.

---

lib/generators/qa/local/tables/mysql/mysql_generator.rb
lib/generators/qa/local/tables/tables_generator.rb

Make local tables generator point at the namespaced table for local authorities

---

config/authorities/linked_data/agrovoc.json
spec/controllers/linked_data_terms_controller_spec.rb
spec/lib/authorities/linked_data/generic_authority_spec.rb

Update Agrovoc URL to latest supported URL

---

lib/qa/authorities/local/file_based_authority.rb
spec/lib/authorities/file_based_authority_spec.rb

adds active flag to terms defaulting to true

---

CONTRIBUTING.md
README.md
SUPPORT.md

- Resolve #166; Update contributing guidelines

Update docs to match templates

---

CHANGELOG.md
app/controllers/qa/application_controller.rb
app/controllers/qa/linked_data_terms_controller.rb
app/controllers/qa/terms_controller.rb
lib/qa/version.rb
spec/fixtures/lexvo_snippet.rdf.xml
spec/lib/services/rdf_authority_parser_spec.rb

Also…
* set up 2.1.1 bugfix release
* fix Error in fixture lexvo_snippet

revert controllers to inherit from including app ApplicationController

---

lib/qa/authorities/getty/aat.rb
lib/qa/authorities/getty/tgn.rb
spec/lib/authorities/getty/aat_spec.rb
spec/lib/authorities/getty/tgn_spec.rb

Applies the equivalent change from PR #178 to TGN and AAT. Also adds multiple term support to AAT for searches with multiple words.

Fixes #179

---

app/services/qa/linked_data/graph_service.rb
lib/qa/authorities/linked_data/search_query.rb
spec/controllers/linked_data_terms_controller_spec.rb
spec/fixtures/lod_search_with_blanknode_subjects.nt
spec/services/linked_data/graph_service_spec.rb

* Fixes bug caught in review of PR #188 
* Adds test that would have revealed the bug.

Add test to catch when blank nodes are not filtered out of search results

---

lib/qa/authorities/getty/aat.rb
lib/qa/authorities/getty/tgn.rb
lib/qa/authorities/getty/ulan.rb
spec/lib/authorities/getty/aat_spec.rb
spec/lib/authorities/getty/tgn_spec.rb
spec/lib/authorities/getty/ulan_spec.rb

Adjust URLs for fetching a single term from getty

---

lib/qa/authorities/base.rb
lib/qa/authorities/web_service_base.rb

* remove `full_record(id, subauth)` from base
* remove `get_json(url)` from web_service_base

Remove older deprecations in preparation for major release

---

lib/qa/version.rb

Creating a release candidate for testing with outside apps (e.g. Hyrax, LD4P qa_server) prior to making full 4.0.0 release.

prep for release candidate 4.0.0.rc1

---

app/services/qa/linked_data/mapper/term_results_mapper_service.rb
config/authorities/linked_data/loc.json
lib/qa/authorities/linked_data/config/term_config.rb
lib/qa/authorities/linked_data/find_term.rb
spec/services/linked_data/mapper/term_results_mapper_service_spec.rb

Final PR refactoring findterm to add ldpath support for selected out results.

Add ldpath for findterm

---

.circleci/config.yml

Updates the CircleCI configuration to test against Ruby releases 2.6.3, 2.5.5, and 2.4.6

---

app/models/qa/linked_data/config/context_property_map.rb
app/services/qa/linked_data/mapper/context_mapper_service.rb
spec/services/linked_data/mapper/context_mapper_service_spec.rb

make it optional whether to include blank values in linked data extended context

---

lib/qa/authorities/getty/tgn.rb
spec/lib/authorities/getty/tgn_spec.rb

Adjust queries for TGN to use TGN scheme and not ULAN

---

.circleci/config.yml

Re: samvera/maintenance#20
Re: samvera/maintenance#21

Remove CircleCI ruby/rails version defaults

---

CHANGELOG.md
lib/qa/version.rb

* add optional response header which has pagination information for DISCOGs search
* add support for Rails 6

prep for release 5.2.0

---

CHANGELOG.md
lib/qa/version.rb

bug fix
* make ip logging more robust when location cannot be retrieved from the request

release 5.3.1

---

CONTRIBUTING.md

Changes references from `master` branch to `main`.
Fixes #340

Update CONTRIBUTING.md to match the maintenance template

---

lib/qa/authorities/oclcts/generic_oclc_authority.rb

In a single file, to make the change to 3.0 easier.

Change open(url) to URI.open(url)

---

lib/qa/authorities/linked_data/find_term.rb

(issue description by jrochkind)
`URI.unescape` does not exist anymore in ruby 3.1, after having been long-deprecated.  
There are a variety of other ways in stdlib to do some kind of html-related `unescape`, but none have the exact same semantics. 
It is hard to know which we want -- when we don't understand why this `unescape` is here in the first place. Why would an in-memory `id` in the `LinkedData::FindTerm` authority be in an escaped form, and need unescaping before doing... other things that honestly we're not sure what they're doing, which doesn't make it easier to know what form of escaping, if any, is necessary here. 
All tests pass without any unescaping, there are no tests that require escaping, so that doesn't answer the question of why escaping is being done here, and what …

Replace URI.unescape with CGI.unescape

---

qa.gemspec

Enable MFA for rubygems

---

.circleci/config.yml

If CI still passes, then we're good.

switch from deprecated circleci orb samvera/bundle_for_gem to current samvera/bundle

---

.circleci/config.yml
spec/lib/authorities/getty/aat_spec.rb
spec/lib/authorities/getty/tgn_spec.rb
spec/lib/authorities/getty/ulan_spec.rb

Part of https://github.com/samvera/maintenance/issues/159

Test with ruby 3.3

---

.circleci/config.yml
qa.gemspec

Let's see if it just passes?
We're still using circle-ci, sheesh, I'm not sure if that will actually still work? We may have to switch to travis. But let's see.

Allow and test on Rails 8.0

---

lib/qa/version.rb

This version should work with Rails 8.0

bump version for 5.14.0
